version: "3.9"

services:
  golang:
    image: golang:1.21
    working_dir: /golang
    command: ["make", "run"]
    volumes:
      - ./:/golang
    env_file:
      - ./.env
    ports:
      - 8080:8080