version: "3.9"

services:
  golang:
    image: golang:1.21
    working_dir: /golang
    command: ["make", "run"]
    volumes:
      - ./:/golang
    env_file:
      - ./.env
    ports:
      - 8080:8080
    networks:
      - golang_network

  mysql:
    platform: linux/x86_64
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    user: root
    networks:
      - golang_network

volumes:
  mysql-data:
    name: mysql-volume

networks:
  golang_network:
    external: true